#######################################################################################
# Book settings
title: Discipline Specific Guidance for DMPs
author: "Discipline Specific Guidance for DMPs - RDA WG"
copyright: "2023"

#######################################################################################
# Launch button settings
repository: 
    url: https://github.com/santoshilam/Discipline_Specific_Guidance_for_DMPs

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : "off"  #Must be one of ("auto", "force", "cache", "off")

only_build_toc_files: true
exclude_patterns            : [_build, Thumbs.db, .DS_Store]
